name: build-android-sidecar

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # =========================
      # Go
      # =========================
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      # =========================
      # Download Android NDK (official)
      # =========================
      - name: Install Android NDK
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip

          mkdir -p $HOME/android-sdk
          cd $HOME/android-sdk

          wget https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
          unzip android-ndk-r26d-linux.zip

          echo "ANDROID_NDK_HOME=$HOME/android-sdk/android-ndk-r26d" >> $GITHUB_ENV

      # =========================
      # Go build
      # =========================
      - name: Build sidecar
        run: |
          cd go-sidecar

          TOOLCHAIN=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64

          export API=21
          export TARGET=aarch64-linux-android

          export CC=$TOOLCHAIN/bin/${TARGET}${API}-clang

          export CGO_ENABLED=1
          export GOOS=android
          export GOARCH=arm64

          go mod tidy
          go build -buildmode=c-shared -o libproxy.so .

      # =========================
      # Upload artifact
      # =========================
      - name: Upload .so
        uses: actions/upload-artifact@v4
        with:
          name: libproxy
          path: go-sidecar/libproxy.so
