name: Build Android Sidecar

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Go build
      working-directory: go-sidecar   # ⭐关键修复
      run: |
        go mod tidy

        export CGO_ENABLED=1
        export GOOS=android
        export GOARCH=arm64

        go build -buildmode=c-shared -o libproxy.so .
